services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: notes
      SPRING_DATASOURCE_USERNAME: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-postgres

  backend:
    build: ./backend/backend
    container_name: spring_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notes
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - spring-postgres

  frontend:
    build: ./frontend
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - spring-postgres

volumes:
  postgres_data:

networks:
  spring-postgres:
    driver: bridge